const CONFIG = {
  DEFAULT_PORT: 8080,
  DEFAULT_HOST: 'localhost',
  SERVER_USERNAME: 'Server',
  MAX_USERNAME: 16,
  MAX_PAYLOAD: 512,
  RATE_PER_SECOND: 2,
  ALLOWED_STRIKES: 3,
  USE_STRIKES_FOR_RATE: true,
  SHUT_DOWN_FORCEFULLY_TIMEOUT: 1000 * 10,
  INACTIVITY_LIMIT: 1000 * 10,
  CHECK_INACTIVITY_FREQUENCY: 2, // Times per INACTIVITY_LIMIT
  USE_INACTIVITY_LIMIT: false,
}
CONFIG.CHECK_INACTIVITY_INTERVAL = CONFIG.INACTIVITY_LIMIT / CONFIG.CHECK_INACTIVITY_FREQUENCY

module.exports = CONFIG