const CONFIG = {
  DEFAULT_PORT: 8080,
  SERVER_USERNAME: 'Server',
  MAX_USERNAME: 16,
  MAX_PAYLOAD: 512,
  RATE_PER_SECOND: 2,
  ALLOWED_STRIKES: 3,
  USE_STRIKES_FOR_RATE: true,
  SHUT_DOWN_FORCEFULLY_TIMEOUT: 1000 * 10,
  INACTIVITY_LIMIT: 1000 * 15, // 15s
  CHECK_INACTIVITY_FREQUENCY: 1, // Times per INACTIVITY_LIMIT
  USE_INACTIVITY_LIMIT: true
}
CONFIG.CHECK_INACTIVITY_INTERVAL =
  CONFIG.INACTIVITY_LIMIT / CONFIG.CHECK_INACTIVITY_FREQUENCY

module.exports = CONFIG
